openapi: 3.0.0
info:
  title: Seconds API
  version: 1.0.0
  description: Welcome to the Seconds API documentation
  license:
    name: Licensed Under MIT
    url: https://spdx.org/licenses/MIT.html
  contact:
    name: JSONPlaceholder
    url: https://jsonplaceholder.typicode.com
servers:
  - url: http://localhost:3001
    description: Development server
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Seconds-Api-Key
  schemas:
    DeliveryRequirements:
      $ref: ./schemas/JobRequirements.json
    Job:
      $ref: ./schemas/Job.json
    UpdateRequirements:
      $ref: ./schemas/JobUpdateRequirements.json
    DeletedJob:
      type: object
      properties:
        code:
          type: integer
        jobId:
          type: string
        cancelled:
          type: boolean
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
  parameters:
    JobId:
      in: path
      name: job_id
      required: true
      description: The id of the requested delivery job
      schema:
        type: string
        example: job_SKDo1qRpUveLU8@NWZ3:ofsC
  requestBodies:
    createJobRequest:
      description: Request body of delivery properties
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeliveryRequirements'
          example:
            pickupAddress: 250 Reede Rd, Dagenham RM10 8EH
            pickupFormattedAddress:
              street: 250 Reede Road
              city: Dagenham
              postcode: RM10 8EH
              countryCode: GB
            pickupPhoneNumber: '+447507210809'
            pickupEmailAddress: chisom.oguibe@googlemail.com
            pickupBusinessName: Humandroid
            pickupFirstName: Chisom
            pickupLastName: Oguibe
            pickupInstructions: N/A
            dropoffAddress: 35 Forresters Apartments 42 Linton Road, Barking, England, IG11 8FS
            dropoffFormattedAddress:
              street: 42 Linton Road
              city: Barking
              postcode: IG11 8FS
              countryCode: GB
            dropoffPhoneNumber: '+447523958055'
            dropoffEmailAddress: olaoladapo7@gmail.com
            dropoffBusinessName: Seconds
            dropoffFirstName: Ola
            dropoffLastName: Oladapo
            dropoffInstructions: Leave in the front porch, if not available
            packageDeliveryMode: Any
            packageDropoffStartTime: 2021-09-30T15:45:14+0000
            packageDropoffEndTime: 2021-09-30T16:00:14+0000
            packagePickupStartTime: 2021-09-30T15:15:14+0000
            packagePickupEndTime: 2021-09-30T15:21:14+0000
            packageDescription: Xbox One S Console
            packageValue: 250
            packageTax: 0.2
            itemsCount: 1
    updateJobRequest:
      description: Request body of delivery properties
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateRequirements'
  responses:
    createJobResponse:
      description: The created job
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Job'
          example:
            createdAt: "2021-09-27T13:06:59.560Z"
            jobId: 6151c1f38a9660a0241d2e06
            jobSpecification:
              id: 100172991
              orderNumber: 0030
              packages:
                - description: Xbox One S Console
                  dropoffLocation:
                    fullAddress: 35 Forresters Apartments 42 Linton Road, Barking, England, IG11 8FS
                    street_address: 42 Linton Road
                    city: Barking
                    postcode: IG11 8FS
                    country: UK
                    phoneNumber: '+447523958055'
                    email: olaoladapo7@gmail.com
                    firstName: Ola
                    lastName: Oladapo
                    businessName: Weezy
                    instructions: Leave in the front porch, if not available
                  dropoffStartTime: 2021-09-10T15:45:14+0000
                  dropoffEndTime: 2021-09-10T16:00:14+0000
                  itemsCount: 1
                  pickupStartTime: 2021-09-10T15:15:14+0000
                  pickupEndTime: 2021-09-10T15:21:14+0000
                  pickupLocation:
                    fullAddress: 250 Reede Rd, Dagenham RM10 8EH
                    city: Dagenham
                    postcode: RM10 8EH
                    country: UK
                    phoneNumber: '+447507210809'
                    email: chisom.oguibe@googlemail.com
                    firstName: Chisom
                    lastName: Oguibe
                    businessName: Seconds Technologies
                    instructions: N/A
                  tax: 0.2
                  value: 250
            selectedConfiguration:
              createdAt: '2021-06-22T18:16:54.025917'
              id: A2G0W*Qu;6D;[*2iEg-ot]6N
              trackingURL: https://stuart.sandbox.followmy.delivery/100216675/ee69dc71a6e496fc6a4a6fe1eb54ba1b
              winnerQuote: quote_4scqrEA,bItf||O9!0c1Qc1k
              providerId: stuart
              quotes:
              - createdTime: '2021-06-22T18:16:56'
                currency: GBP
                dropoffEta: '2021-09-22T19:52:56'
                expireTime: '2021-09-22T18:21:56'
                id: quote_4scqrEA,bItf||O9!0c1Qc1k
                pickupWindow: '2021-06-22T18:16:56.361353'
                price: 13.04
                providerId: stuart
              - createdTime: '2021-06-22T18:16:56'
                currency: GBP
                dropoffEta: '2021-09-22T19:52:56'
                expireTime: '2021-09-22T18:21:56'
                id: quote_4scqrEA@bItf21cewaxc
                pickupWindow: '2021-06-22T18:16:56.361353'
                price: 13.04
                providerId: gophr
            status: CREATED
    requestedJobResponse:
      description: The requested job
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Job'
          example:
            createdAt: "2021-09-27T13:06:59.560Z"
            jobId: 6151c1f38a9660a0241d2e06
            jobSpecification:
              id: 100172991
              orderNumber: 0030
              packages:
                - description: Xbox One S Console
                  dropoffLocation:
                    fullAddress: 35 Forresters Apartments 42 Linton Road, Barking, England, IG11 8FS
                    street_address: 42 Linton Road
                    city: Barking
                    postcode: IG11 8FS
                    country: UK
                    phoneNumber: '+447523958055'
                    email: olaoladapo7@gmail.com
                    firstName: Ola
                    lastName: Oladapo
                    businessName: Weezy
                    instructions: Leave in the front porch, if not available
                  dropoffStartTime: 2021-09-30T15:45:14+0000
                  dropoffEndTime: 2021-09-30T16:00:14+0000
                  itemsCount: 1
                  pickupStartTime: 2021-09-30T15:15:14+0000
                  pickupEndTime: 2021-09-30T15:21:14+0000
                  pickupLocation:
                    fullAddress: 250 Reede Rd, Dagenham RM10 8EH
                    city: Dagenham
                    postcode: RM10 8EH
                    country: UK
                    phoneNumber: '+447507210809'
                    email: chisom.oguibe@googlemail.com
                    firstName: Chisom
                    lastName: Oguibe
                    businessName: Seconds Technologies
                    instructions: N/A
                  tax: 0.2
                  value: 250
            selectedConfiguration:
              createdAt: '2021-06-22T18:16:54.025917'
              id: A2G0W*Qu;6D;[*2iEg-ot]6N
              trackingURL: https://stuart.sandbox.followmy.delivery/100216675/ee69dc71a6e496fc6a4a6fe1eb54ba1b
              winnerQuote: quote_4scqrEA,bItf||O9!0c1Qc1k
              providerId: stuart
              quotes:
                - createdTime: '2021-06-22T18:16:56'
                  currency: GBP
                  dropoffEta: '2021-09-22T19:52:56'
                  expireTime: '2021-09-22T18:21:56'
                  id: quote_4scqrEA,bItf||O9!0c1Qc1k
                  pickupWindow: '2021-06-22T18:16:56.361353'
                  price: 13.04
                  providerId: stuart
                - createdTime: '2021-06-22T18:16:56'
                  currency: GBP
                  dropoffEta: '2021-09-22T19:52:56'
                  expireTime: '2021-09-22T18:21:56'
                  id: quote_4scqrEA@bItf21cewaxc
                  pickupWindow: '2021-06-22T18:16:56.361353'
                  price: 13.04
                  providerId: gophr
            status: CREATED
    updatedJobResponse:
      description: The updated job
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Job'
          example:
            createdAt: "2021-09-27T13:06:59.560Z"
            jobId: 6151c1f38a9660a0241d2e06
            jobSpecification:
              id: 100172991
              orderNumber: 0030
              packages:
                - description: Xbox One S Console
                  dropoffLocation:
                    fullAddress: 35 Forresters Apartments 42 Linton Road, Barking, England, IG11 8FS
                    street_address: 42 Linton Road
                    city: Barking
                    postcode: IG11 8FS
                    country: UK
                    phoneNumber: '+447523958055'
                    email: olaoladapo7@gmail.com
                    firstName: Ola
                    lastName: Oladapo
                    businessName: Weezy
                    instructions: Enter reception area
                  dropoffStartTime: 2021-09-10T15:45:14+0000
                  dropoffEndTime: 2021-09-10T16:00:14+0000
                  itemsCount: 1
                  pickupStartTime: 2021-09-10T15:15:14+0000
                  pickupEndTime: 2021-09-10T15:21:14+0000
                  pickupLocation:
                    fullAddress: 250 Reede Rd, Dagenham RM10 8EH
                    city: Dagenham
                    postcode: RM10 8EH
                    country: UK
                    phoneNumber: '+447507210809'
                    email: chisom.oguibe@googlemail.com
                    firstName: Chisom
                    lastName: Oguibe
                    businessName: Seconds Technologies
                    instructions: N/A
                  tax: 0.2
                  value: 250
            selectedConfiguration:
              createdAt: '2021-06-22T18:16:54.025917'
              id: A2G0W*Qu;6D;[*2iEg-ot]6N
              trackingURL: https://stuart.sandbox.followmy.delivery/100216675/ee69dc71a6e496fc6a4a6fe1eb54ba1b
              winnerQuote: quote_4scqrEA,bItf||O9!0c1Qc1k
              providerId: stuart
              quotes:
                - createdTime: '2021-06-22T18:16:56'
                  currency: GBP
                  dropoffEta: '2021-09-22T19:52:56'
                  expireTime: '2021-09-22T18:21:56'
                  id: quote_4scqrEA,bItf||O9!0c1Qc1k
                  pickupWindow: '2021-06-22T18:16:56.361353'
                  price: 13.04
                  providerId: stuart
                - createdTime: '2021-06-22T18:16:56'
                  currency: GBP
                  dropoffEta: '2021-09-22T19:52:56'
                  expireTime: '2021-09-22T18:21:56'
                  id: quote_4scqrEA@bItf21cewaxc
                  pickupWindow: '2021-06-22T18:16:56.361353'
                  price: 13.04
                  providerId: gophr
            status: DISPATCHING
    deletedJobResponse:
      description: Confirmation of cancelled job
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeletedJob'
          example:
            code: 200
            jobId: job_L*m{ko5zw$zG*gF.5)XacE0}
            cancelled: true
    401Unauthorized:
      description: The API key is missing in the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 401
            message: No valid API key provided!
    403Forbidden:
      description: The API key passed is invalid or does not have the right permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 403
            message: Invalid API Key!
    404NotFound:
      description: The requested delivery job could not be found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 404
            message: 'No job found with ID: job_SKDo1qRpUveLU8@NWZ3:ofsC'
security:
  - ApiKeyAuth: []
tags:
  - name: Jobs
    description: API endpoints for delivery jobs
paths:
  /api/v1/jobs/create:
    post:
      tags:
        - Jobs
      description: Creates a new delivery job. Delivery jobs are assigned with a status to indicate the stage of the delivery process
      summary: API endpoint for creating new delivery jobs.
      requestBody:
        $ref: '#/components/requestBodies/createJobRequest'
      responses:
        '200':
          $ref: '#/components/responses/createJobResponse'
        '401':
          $ref: '#/components/responses/401Unauthorized'
  /api/v1/jobs/{job_id}:
    get:
      tags:
        - Jobs
      parameters:
        - $ref: '#/components/parameters/JobId'
      summary: API endpoint for retrieving a delivery job
      description: ''
      responses:
        '200':
          $ref: '#/components/responses/requestedJobResponse'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
    patch:
      tags:
        - Jobs
      description: ''
      summary: API endpoint for updating details of a delivery job
      parameters:
        - $ref: '#/components/parameters/JobId'
      requestBody:
        $ref: '#/components/requestBodies/updateJobRequest'
      responses:
        '200':
          $ref: '#/components/responses/updatedJobResponse'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
    delete:
      tags:
        - Jobs
      description: ''
      summary: API endpoint for cancelling a delivery job
      parameters:
        - $ref: '#/components/parameters/JobId'
      responses:
        '200':
          $ref: '#/components/responses/deletedJobResponse'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
